name: Update games.json

on:
  push:
    paths:
      - "*.pck"

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate games.json
        run: |
          find . -maxdepth 1 -type f -name "*.pck" -printf "%f\n" \
          | sort \
          | jq -R . \
          | jq -s . > games.json

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add games.json

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Auto-update games.json"
          git push
